# config/packages/doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        default_entity_manager: default #set the default entity manager to use the main database 
        entity_managers:   
            default:
                connection: default #set the default entity manager  to use the default connection
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: App
                dql:
                    string_functions:
                        JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                        JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains