hakam_multi_tenancy:
  tenant_database_className:  App\Entity\Main\TenantDb    # tenant dbs configuration Class Name
  tenant_database_identifier: id                                 # tenant db column name to get db configuration
  tenant_connection:                                             # tenant entity manager connection configuration
    host:     mysql
    driver:   pdo_mysql
    charset:  utf8mb4

  tenant_migration:                                             # tenant db migration configurations, Its recommended to have a different migration for tenants dbs than you main migration config
    tenant_migration_namespace: DoctrineMigrations\Tenant
    tenant_migration_path: migrations/Tenant
  tenant_entity_manager:                                        # tenant entity manger configuration , which is used to manage tenant entities
    dql:
        string_functions:
          test_string: App\DQL\StringFunction
          second_string: App\DQL\SecondStringFunction
          JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
          JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
        numeric_functions:
          test_numeric: App\DQL\NumericFunction
        datetime_functions:
          test_datetime: App\DQL\DatetimeFunction
    mapping:
      type:   attribute                           # mapping type default annotation
      dir:   '%kernel.project_dir%/src/Entity/Tenant'           # directory of tenant entities, it could be different from main directory
      prefix: App\Entity\Tenant                                # tenant entities prefix  ex "App\Entity\Tenant"
      alias:   Tenant                                           # tenant entities alias  ex "Tenant"