# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\LocatorService:
        arguments:
            $locator: "@service_container"

    App\Service\AuthService:
        tags: ['app.service_auth']
        public: true

    App\Service\TeamService:
        public: true

    App\Listeners\ConnectionHandler:
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }

    App\Listeners\TaskStatusHandler:
        tags:
            - {name: 'doctrine.event_listener', event: 'onFlush', priority: 500}

    App\Listeners\TaskMetricsHandler:
        tags:
            - {name: 'doctrine.event_listener', event: 'onFlush', priority: 600}

    App\Listeners\OnAccountLoadSubscriber:
        tags:
            - { name: doctrine.event_subscriber}

    App\Listeners\OnAccountDeleteSubscriber:
        tags:
            - { name: doctrine.event_subscriber}

    App\Listeners\OnRoleProfilePersist:
        tags:
            - {name: doctrine.event_subscriber}

    App\Listeners\OnRoleProfileDelete:
        tags:
            - {name: doctrine.event_subscriber}

    App\Listeners\OnAccountRoleProfilePersist:
        tags:
            - {name: doctrine.event_subscriber}

    App\Listeners\OnTeamLoad:
        tags:
            - {name: doctrine.event_subscriber}

    App\Command\InitProjectCommand:
        tags: ['console.command']

    App\Form\TeamMembersConstraintValidator:
        tags: {name: validator.constraint_validator}

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

imports:
    - {resource: 'services/roles.yaml'}
    - {resource: 'services/search.yaml'}
    - {resource: 'services/filters.yaml'}
    - {resource: 'services/csv.yaml'}
