parameters:
  role_list:
    - ROLE_MODULE_PROJECT
    - ROLE_PROJECT_PROJECT_CREATE
    - ROLE_PROJECT_PROJECT_ACCESS
    - ROLE_PROJECT_PROJECT_EDIT
    - ROLE_PROJECT_PROJECT_DELETE
    - ROLE_PROJECT_TASK_CREATE
    - ROLE_PROJECT_TASK_ACCESS
    - ROLE_PROJECT_TASK_EDIT
    - ROLE_PROJECT_TASK_DELETE
    - ROLE_PROJECT_TASK_ASSIGN
    - ROLE_PROJECT_TEAM_CREATE
    - ROLE_PROJECT_TEAM_ACCESS
    - ROLE_PROJECT_TEAM_EDIT
    - ROLE_PROJECT_TEAM_DELETE

    - ROLE_MODULE_PERSONAL
    - ROLE_PERSONAL_PROFILE_CREATE
    - ROLE_PERSONAL_PROFILE_ACCESS
    - ROLE_PERSONAL_PROFILE_EDIT
    - ROLE_PERSONAL_PROFILE_DELETE
    - ROLE_PERSONAL_ROLE_CREATE
    - ROLE_PERSONAL_ROLE_ACCESS
    - ROLE_PERSONAL_ROLE_EDIT
    - ROLE_PERSONAL_ROLE_DELETE