parameters:
  search:
    App\Entity\Tenant\RoleProfile:
      fields:
        name:
          method: like
    App\Entity\Main\Profile:
      fields:
        firstname:
          method: like
        lastName:
          method: like
        username:
          method: like
    App\Entity\Tenant\Team:
      fields:
        name:
          method: like

